spring:
  application:
    name: SpringSecurityProject

  datasource:
    url: jdbc:mysql://localhost:3306/secure_vault
    username: root
    password: Ratanlord@1409
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: Ratnakar
      password: Ratanlord@1409

# Server configuration
server:
  port: 8091   # Application will run on port 8091

  servlet:
    session:
      cookie:
        # SameSite attribute controls when browser sends the session cookie (JSESSIONID)

        # STRICT:
        # Cookie is sent ONLY when request originates from the same site.
        # It will NOT be sent for:
        # - Cross-site links
        # - External redirects
        # - Requests from other domains
        # Provides highest CSRF protection.
        same-site: STRICT

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE